### ISSUE TITLE
Data sensors

### ISSUE THREAD

**Issue by cruelneo** [sunnyhaibin/openpilot#14]
2020 palisade with sunnyhaibin none personal keeps getting data sensor issue after install. Won’t engage it also says unable to detect car closes car is 2020 palisade.

**Comment by sunnyhaibin** [comment]
Hi, this issue should be fixed in the latest release of sunnypilot. Please install the below branches:
- [0.8.12-prod-full-hkg](https://github.com/sunnyhaibin/openpilot/tree/0.8.12-prod-full-hkg)
- [0.8.12-prod-personal-hkg](https://github.com/sunnyhaibin/openpilot/tree/0.8.12-prod-personal-hkg)
